title: Default Page

tabs:
    content:
        label: Περιεχόμενο
        icon: text
        columns:
          - width: 2/3
            sections:
                content:
                    type: fields
                    fields:
                        body:
                            extends: fields/fulleditor

          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles
    seo: tabs/seo
    message: tabs/message
