title: Services Page

tabs:
    content:
        label: Περιεχόμενο
        icon: text
        columns:
          - width: 2/3
            sections:
                services:
                    type: fields
                    fields:
                        services:
                            label: Υπηρεσίες
                            type: structure
                            fields:
                                title:
                                    label: Τίτλος
                                    type: text
                                body:
                                    extends: fields/editor
                                    label: Περιγραφή
                                coverimage:
                                    extends: fields/image
                                    label: Εικόνα
          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles
    seo: tabs/seo
    message: tabs/message
